# Generated by Django 5.0.6 on 2024-07-07 10:37

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default=core.models.default_image, null=True, upload_to='images/profilepictures/'),
        ),
    ]
