# Generated by Django 5.0.6 on 2024-07-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioneros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='features_content',
            name='large_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/featurelargeimage/'),
        ),
    ]
