# Generated by Django 5.0.6 on 2024-07-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioneros', '0002_features_content_large_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='features_content',
            name='large_image',
        ),
        migrations.AddField(
            model_name='feature',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/featureimage/'),
        ),
    ]
