# Generated by Django 5.0.6 on 2024-07-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioneros', '0004_news_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAndEventBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/newsandeventbackground/')),
            ],
        ),
    ]
